from setuptools import setup

setup(name='Poornamer',
      version='0.0.1',
      description='Poornamer',
      author='Spray Idle',
      author_email='sprayidle@gmail.com',
      url='',
      install_requires=['Flask==0.10.1',
	                    # 'PyRSS2Gen==1.1',
						# 'beautifulsoup4==4.4.0',
						# 'requests>=2.7.0',
						# 'html5lib==0.999999',
						# 'pocket==0.3.5',
						'Flask-SQLAlchemy==2.0',
						# 'cryptography==0.9.3',
						# 'ndg-httpsclient==0.4.0',
						# 'pyOpenSSL==0.15.1',
						# 'Flask-Migrate==1.2.0',
						# 'Flask-Limiter==0.6.6',
						# 'Flask-Login==0.2.11',
						# 'lxml==3.4.1',
						# 'feedparser==5.1.3',
						],
     )
